version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: rickandmorty
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data