spring:
  datasource:
    url: jdbc:mysql://localhost:3306/COPERNICO?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: developer
    password: developer
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    locations: classpath:db/migration
