spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rickandmorty
    username: developer
    password: developer
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: classpath:db/migration
